# Generated by Django 4.1.2 on 2022-10-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='mark',
            field=models.CharField(choices=[(None, 'Your String For Display'), ('1', 'Bad'), ('2', 'Good'), ('3', 'Very Good')], max_length=50),
        ),
    ]
